using TaskFlow.Domain.Common;
using TaskFlow.Domain.Enums;

namespace TaskFlow.Domain.Entities;

/// <summary>
/// Immutable audit-trail record describing a single action taken on a
/// Project or TaskItem (created, status changed, assigned, commented, etc).
/// Powers the "Activity History" timeline UI. Records are never updated or
/// deleted once written - only ever inserted (append-only log).
/// </summary>
public class ActivityLog : BaseEntity
{
    public ActivityActionType ActionType { get; set; }

    /// <summary>
    /// Human-readable description of what happened, e.g.
    /// "changed status from To Do to In Progress".
    /// Generated by the service layer at the time of the action.
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Optional JSON snapshot of the old/new values for fields that changed,
    /// useful for detailed audit views without needing extra columns per field.
    /// </summary>
    public string? MetadataJson { get; set; }

    public EntityRelationType RelatedTo { get; set; }

    public int? ProjectId { get; set; }
    public Project? Project { get; set; }

    public int? TaskItemId { get; set; }
    public TaskItem? TaskItem { get; set; }

    public string UserId { get; set; } = string.Empty;
    public ApplicationUser User { get; set; } = null!;
}
